on:
    push:
      branches:
      - develop
    pull_request:
      branches:
      - main
jobs:
    build:
      runs-on: ubuntu-latest
      timeout-minutes: 15
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set VERSION variable from tag
        run: echo "VERSION=1.0.0-ci.${{github.run_number}}" >> $GITHUB_ENV
      - name: Build
        run: dotnet pack /p:Version=${VERSION} -o Output/ --configuration Release
      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: Output/