on:
    push:
      tags:
      - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9][0-9][0-9]"
jobs:
    build:
      runs-on: ubuntu-latest
      timeout-minutes: 15
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --output .
      - name: Authenticate to GitHub Packages
        run: dotnet nuget add source --username TheUltimateNuke --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/GBMTemplates/index.json"  
      - name: Push to GitHub Packages
        run: dotnet nuget push GBMTemplates.${VERSION}.nupkg --source https://nuget.pkg.github.com/GBMTemplates/index.json --api-key ${GITHUB_TOKEN}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}