on:
    push:
      tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
    build:
      runs-on: ubuntu-latest
      timeout-minutes: 15
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/GBMTemplates/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Verify commit exists in origin/main
        run: git branch --remote --contains | grep origin/main
      - name: Extract release notes
        run: |
          git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}
      - name: Test
        run: dotnet test --configuration Release /p:Version=${VERSION} --no-build
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} --output .
      - name: Push to GitHub Packages
        run: dotnet nuget push GBMTemplates.${VERSION}.nupkg
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}